"""compliance_checks

Revision ID: 1215c407390f
Revises: 9dc6c063ed22
Create Date: 2026-06-29 05:23:05.616194
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1215c407390f'
down_revision: str | None = '9dc6c063ed22'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_checks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('content_item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('deliverable_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('risk', sa.Enum('pass', 'warn', 'block', name='compliance_risk'), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_content_item_id'), 'compliance_checks', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_compliance_checks_risk'), 'compliance_checks', ['risk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_checks_risk'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_content_item_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    # PostgreSQL: drop_table 不会删除 ENUM 类型，需显式删除，否则重新 upgrade 报 "type already exists"
    op.execute("DROP TYPE IF EXISTS compliance_risk")
    # ### end Alembic commands ###
