"""metric_snapshots

Revision ID: b670de6443ef
Revises: 1215c407390f
Create Date: 2026-06-29 05:34:08.951700
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b670de6443ef'
down_revision: str | None = '1215c407390f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('content_item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('source', sa.Enum('douyin', 'xiaohongshu', 'shipinhao', 'manual', 'demo', name='metric_source'), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('play', sa.Integer(), nullable=False),
    sa.Column('exposure', sa.Integer(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.Column('like_rate', sa.Float(), nullable=False),
    sa.Column('comment_rate', sa.Float(), nullable=False),
    sa.Column('share_rate', sa.Float(), nullable=False),
    sa.Column('follower_delta', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_snapshots_account_id'), 'metric_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_content_item_id'), 'metric_snapshots', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_org_id'), 'metric_snapshots', ['org_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_stat_date'), 'metric_snapshots', ['stat_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_snapshots_stat_date'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_org_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_content_item_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_account_id'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    # PostgreSQL: drop_table 不会删除 ENUM 类型，需显式删除，否则重新 upgrade 报 "type already exists"
    op.execute("DROP TYPE IF EXISTS metric_source")
    # ### end Alembic commands ###
