"""llm call log

Revision ID: 9dc6c063ed22
Revises: 9e483052ec78
Create Date: 2026-06-26 15:58:28.074844
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc6c063ed22'
down_revision: str | None = '9e483052ec78'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('agent_code', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_agent_code'), 'llm_calls', ['agent_code'], unique=False)
    op.create_index(op.f('ix_llm_calls_model'), 'llm_calls', ['model'], unique=False)
    op.create_index(op.f('ix_llm_calls_org_id'), 'llm_calls', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_calls_org_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_model'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_agent_code'), table_name='llm_calls')
    op.drop_table('llm_calls')
    # ### end Alembic commands ###
