"""material_assets

Revision ID: eeea13a2d75d
Revises: b670de6443ef
Create Date: 2026-06-29 06:15:08.616477
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeea13a2d75d'
down_revision: str | None = 'b670de6443ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_assets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('org_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('content_item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('deliverable_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('queued', 'generating', 'ready', 'failed', name='material_status'), nullable=False),
    sa.Column('external_task_id', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.String(length=512), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_assets_content_item_id'), 'material_assets', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_material_assets_deliverable_id'), 'material_assets', ['deliverable_id'], unique=False)
    op.create_index(op.f('ix_material_assets_org_id'), 'material_assets', ['org_id'], unique=False)
    op.create_index(op.f('ix_material_assets_status'), 'material_assets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_assets_status'), table_name='material_assets')
    op.drop_index(op.f('ix_material_assets_org_id'), table_name='material_assets')
    op.drop_index(op.f('ix_material_assets_deliverable_id'), table_name='material_assets')
    op.drop_index(op.f('ix_material_assets_content_item_id'), table_name='material_assets')
    op.drop_table('material_assets')
    # PostgreSQL: drop_table 不会删除 ENUM 类型，需显式删除，否则重新 upgrade 报 "type already exists"
    op.execute("DROP TYPE IF EXISTS material_status")
    # ### end Alembic commands ###
